services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/postgres
      - PAGE_COUNT=30
      - ALL_CATEGORY_ID=0
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
